 export const pictures = [
    {
        id: '1',
        name: 'Les Nymphéas',
        artist: 'Claude Monet',
        date: '1914 - 1926',
        type: 'Huile sur toile',
        size: '219 x 602 cm',
        museum: 'Musée de l\'Orangerie, Paris',
    },
    {
        id: '2',
        name: 'Paysage avec une rivière et une baie dans le lointain',
        artist: 'William Turner',
        date: '1845',
        type: 'Huile sur toile',
        size: '93 x 123 cm',
        museum: 'Musée du Louvre, Paris',
    },
    {
        id: '3',
        name: 'La Joconde',
        artist: 'Léonard De Vinci',
        date: '1503 - 1519',
        type: 'Huile sur panneau de bois de peuplier',
        size: '77 x 53 cm',
        museum: 'Musée du Louvre, Paris',
    },
    {
        id: '4',
        name: 'La Naissance de Vénus',
        artist: 'Sandro Botticelli',
        date: '1484 - 1485',
        type: 'Tempera',
        size: '1,725 x 2,785 m',
        museum: 'Galerie des Offices, Florence',
    },
    {
        id: '5',
        name: 'La Cène',
        artist: 'Léonard De Vinci',
        date: '1495 - 1498',
        type: 'Tempera sur gesso',
        size: '460 x 880 cm',
        museum: 'Église Santa Maria delle Grazie',
    },
    {
        id: '6',
        name: 'La Nuit étoilée',
        artist: 'Vincent van Gogh',
        date: '1889',
        type: 'Huile sur toile',
        size: '74 x 92 cm',
        museum: 'MOMA, New York',
    },
    {
        id: '7',
        name: 'La Jeune Fille à la perle',
        artist: 'Johannes Vermeer',
        date: '1665',
        type: 'Huile sur toile',
        size: '44,5 x 39 cm',
        museum: 'Mauritshuis, La Haye',
    },
    {
        id: '8',
        name: 'American Gothic',
        artist: 'Grant Wood',
        date: '1930',
        type: 'Huile sur isorel mou',
        size: '78 x 65,3 cm',
        museum: 'Art Institute of Chicago, Chicago',
    },
    {
        id: '9',
        name: 'Bal du moulin de la Galette',
        artist: 'Auguste Renoir',
        date: '1876',
        type: 'Huile sur toile',
        size: '131 x 175 cm',
        museum: 'Musée d\'Orsay, Paris',
    },
    {
        id: '10',
        name: 'La Grande Vague de Kanagawa',
        artist: 'Hokusai',
        date: '1830',
        type: 'Estampe japonaise',
        size: '25,7 x 37,9 cm',
        museum: 'MOMA, New York',
    },
    {
        id: '11',
        name: 'Le Désespéré',
        artist: 'Gustave Courbet',
        date: '1843 - 1845',
        type: 'Huile sur toile',
        size: '45 x 54 cm',
        museum: 'Collection particulière',
    },
    {
        id: '12',
        name: 'La Liberté guidant le peuple',
        artist: 'Eugène Delacroix',
        date: '1830',
        type: 'Peinture à l\'huile',
        size: '260 x 325 cm',
        museum: 'Musée du Louvre, Paris',
    },
]